Repository kobe860219/ntcuba-frontend, pull requests merged in 2021-08, with the labels that each got.

#3 NTCUBA-2. Add countributing doc
  docs/contributing.md
Labels: documentation

#5 NTCUBA-4. Add ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE.md
Labels: documentation, enhancement

#7 NTCUBA-6. Update github action file for angular app
  .eslintrc.json
  .github/workflows/main.yaml
  angular.json
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/spec.ts
  cypress/plugins/index.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
Labels: improvement

#8 Update readme.md
  README.md
Labels: documentation

#9 ReadME add Testing txt
  README.md
Labels: documentation

#10 test read.me
  README.md
Labels: documentation

#15 Test issue
  README.md
  src/app/app.component.ts
Labels: documentation
